[package]
name = "voxi-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "voxi_server"
path = "src/lib.rs"

[[bin]]
name = "voxi-server"
path = "src/main.rs"

[dependencies]
voxi-proto = { path = "../voxi-proto" }
voxi-room = { path = "../voxi-room" }
axum = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libsql = "0.6"
tower-http = { version = "0.6", features = ["cors", "fs"] }
jsonwebtoken = "9"
dotenvy = "0.15"

[dev-dependencies]
tokio-tungstenite = { workspace = true }
futures-util = "0.3"
